wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1708469833.332333
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 2
      - 23
      4: 3.11.4
      5: 0.16.3
      8:
      - 1
      - 5
      13: linux-x86_64
