name: aims-visibility
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.10=h7f8727e_2
  - pip=23.2.1=py311h06a4308_0
  - python=3.11.4=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py311h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - aiohttp==3.8.5
    - aiosignal==1.3.1
    - annotated-types==0.5.0
    - anyio==4.0.0
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - arxiv==1.4.8
    - asttokens==2.4.0
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - babel==2.12.1
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - cachetools==5.3.1
    - certifi==2023.7.22
    - cffi==1.15.1
    - charset-normalizer==3.2.0
    - click==8.1.7
    - coloredlogs==15.0.1
    - comm==0.1.4
    - contourpy==1.2.0
    - cryptography==41.0.3
    - cycler==0.12.1
    - dataclasses-json==0.5.14
    - debugpy==1.6.7.post1
    - decorator==5.1.1
    - defusedxml==0.7.1
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - executing==1.2.0
    - faiss-cpu==1.7.4
    - fastjsonschema==2.18.0
    - feedparser==6.0.10
    - filelock==3.12.3
    - flatbuffers==23.5.26
    - fonttools==4.49.0
    - fqdn==1.5.1
    - frozenlist==1.4.0
    - fsspec==2023.9.0
    - gitdb==4.0.10
    - gitpython==3.1.34
    - gptcache==0.1.40
    - greenlet==2.0.2
    - h11==0.14.0
    - hiredis==2.2.3
    - httpcore==1.0.3
    - httpx==0.26.0
    - huggingface-hub==0.16.4
    - humanfriendly==10.0
    - idna==3.4
    - ipykernel==6.25.2
    - ipython==8.15.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.1.0
    - isoduration==20.11.0
    - jedi==0.19.0
    - jinja2==3.1.2
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.0
    - jsonschema-specifications==2023.7.1
    - jupyter==1.0.0
    - jupyter-client==8.3.1
    - jupyter-console==6.6.3
    - jupyter-core==5.3.1
    - jupyter-events==0.7.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.7.3
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.5
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.24.0
    - jupyterlab-widgets==3.0.8
    - kiwisolver==1.4.5
    - langchain==0.0.283
    - langsmith==0.0.33
    - markupsafe==2.1.3
    - marshmallow==3.20.1
    - matplotlib==3.8.3
    - matplotlib-inline==0.1.6
    - mistune==3.0.1
    - more-itertools==9.1.0
    - mpmath==1.3.0
    - multidict==6.0.4
    - mypy-extensions==1.0.0
    - nbclient==0.8.0
    - nbconvert==7.8.0
    - nbformat==5.9.2
    - nest-asyncio==1.5.7
    - notebook==7.0.3
    - notebook-shim==0.2.3
    - numexpr==2.8.5
    - numpy==1.26.4
    - onnxruntime==1.15.1
    - openai==1.12.0
    - overrides==7.4.0
    - packaging==23.1
    - pandas==2.2.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathtools==0.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.2.0
    - platformdirs==3.10.0
    - plotly==5.19.0
    - prometheus-client==0.17.1
    - prompt-toolkit==3.0.39
    - protobuf==4.24.2
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pydantic==2.0.3
    - pydantic-core==2.3.0
    - pygments==2.16.1
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - python-dotenv==1.0.1
    - python-json-logger==2.0.7
    - python-ulid==1.1.0
    - pytz==2024.1
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - qtconsole==5.4.4
    - qtpy==2.4.0
    - redis==3.5.3
    - redis-om==0.2.1
    - redisearch==2.1.1
    - referencing==0.30.2
    - regex==2023.8.8
    - rejson==0.5.6
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.2
    - safetensors==0.3.3
    - scikit-learn==1.4.1.post1
    - scipy==1.12.0
    - send2trash==1.8.2
    - sentry-sdk==1.30.0
    - setproctitle==1.3.2
    - sgmllib3k==1.0.0
    - six==1.16.0
    - smmap==5.0.0
    - sniffio==1.3.0
    - soupsieve==2.5
    - sqlalchemy==2.0.20
    - stack-data==0.6.2
    - sympy==1.12
    - tenacity==8.2.3
    - terminado==0.17.1
    - threadpoolctl==3.3.0
    - tiktoken==0.4.0
    - tinycss2==1.2.1
    - tokenizers==0.13.3
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.9.0
    - transformers==4.33.0
    - types-pyopenssl==23.2.0.2
    - types-redis==4.6.0.5
    - typing-extensions==4.7.1
    - typing-inspect==0.9.0
    - tzdata==2024.1
    - uri-template==1.3.0
    - urllib3==2.0.4
    - wandb==0.16.3
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.2
    - widgetsnbextension==4.0.8
    - yarl==1.9.2
prefix: /home/chris/anaconda3/envs/aims-visibility
